[package]
name = "dotfiles"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
chrono = "0.4.43"
common = { workspace = true }
clap = { version = "4.5.54", features = ["derive", "string"] }
clap_complete = { version = "4.5.65", features = ["unstable-dynamic"] }
dirs = "6.0.0"
execute = "0.2.15"
fastrand = "2.3.0"
hyprland = "0.4.0-beta.3"
itertools = "0.14.0"
niri-ipc = "25.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
wallust_themes = "1.1.0"

[build-dependencies]
clap = { version = "4.5.54", features = ["derive", "string"] }
clap_complete = { version = "4.5.65", features = ["unstable-dynamic"] }
clap_mangen = "0.2.31"
