[helium]
src.github_tag = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"

[mpv-cut]
src.git = "https://github.com/familyfriendlymikey/mpv-cut"
fetch.github = "familyfriendlymikey/mpv-cut"

[mpv-deletefile]
src.git = "https://github.com/zenyd/mpv-scripts"
fetch.github = "zenyd/mpv-scripts"

[mpv-nextfile]
src.git = "https://github.com/jonniek/mpv-nextfile"
fetch.github = "jonniek/mpv-nextfile"

[mpv-sub-select]
src.git = "https://github.com/CogentRedTester/mpv-sub-select"
fetch.github = "CogentRedTester/mpv-sub-select"

[mpv-subsearch]
src.git = "https://github.com/kelciour/mpv-scripts"
fetch.github = "kelciour/mpv-scripts"

[rofi-themes]
src.git = "https://github.com/adi1090x/rofi"
fetch.github = "adi1090x/rofi"

# [swww]
# src.git = "https://github.com/Horus645/swww"
# # src.manual = "9a012646e66420ab8058b9f595cdfa0c14625755"
# fetch.github = "LGFae/swww"

# [wallust]
# src.git = "https://codeberg.org/explosion-mental/wallust"
# # src.manual = "549b30dae0ae9db0bdda780a17d474562378399f"
# fetch.git = "https://codeberg.org/explosion-mental/wallust"

[yazi-plugins]
src.git = "https://github.com/yazi-rs/plugins"
fetch.github = "yazi-rs/plugins"

[yazi-time-travel]
src.git = "https://github.com/iynaix/time-travel.yazi"
fetch.github = "iynaix/time-travel.yazi"

[yt-dlp]
src.github_tag = "yt-dlp/yt-dlp"
fetch.github = "yt-dlp/yt-dlp"
