[package]
name = "common"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
niri-ipc = "25.11.0"
rayon = "1.11.0"
regex = "1.12.2"
rexiv2 = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = "0.4.43"
csv = "1.4.0"
clap = { version = "4.5.54", features = ["derive", "string"] }
clap_complete = { version = "4.5.65", features = ["unstable-dynamic"] }
dirs = "6.0.0"
execute = "0.2.15"
fast_image_resize = { version = "6.0.0", features = ["image", "rayon"] }
fastrand = "2.3.0"
hyprland = "0.4.0-beta.3"
image = "0.25.9"
itertools = "0.14.0"
wallust_themes = "1.1.0"
