[path-of-building]
src.github_tag = "PathOfBuildingCommunity/PathOfBuilding"
fetch.github = "PathOfBuildingCommunity/PathOfBuilding"

[swww]
src.git = "https://github.com/Horus645/swww"
# src.manual = "9a012646e66420ab8058b9f595cdfa0c14625755"
fetch.github = "LGFae/swww"

[wallust]
src.git = "https://codeberg.org/explosion-mental/wallust"
# src.manual = "549b30dae0ae9db0bdda780a17d474562378399f"
fetch.git = "https://codeberg.org/explosion-mental/wallust"

[yt-dlp]
src.github_tag = "yt-dlp/yt-dlp"
fetch.github = "yt-dlp/yt-dlp"

[zfs-yazi]
src.git = "https://github.com/iynaix/zfs.yazi"
fetch.github = "iynaix/zfs.yazi"
