[hyprlock]
src.git = "https://github.com/hyprwm/hyprlock"
fetch.github = "hyprwm/hyprlock"

[mpv-dynamic-crop]
src.git = "https://github.com/Ashyni/mpv-scripts"
fetch.github = "Ashyni/mpv-scripts"

[path-of-building]
src.github_tag = "PathOfBuildingCommunity/PathOfBuilding"
fetch.github = "PathOfBuildingCommunity/PathOfBuilding"

[swww]
# src.git = "https://github.com/Horus645/swww"
src.manual = "432b7135af0bb34e4b0e55edf76ff516937bc7b0"
fetch.github = "LGFae/swww"

[wallust]
src.git = "https://codeberg.org/explosion-mental/wallust.git"
# src.branch = "dev"
fetch.git = "https://codeberg.org/explosion-mental/wallust.git"
